spring:
  application:
    name: rest-api
  datasource:
    url: jdbc:postgresql://localhost:5432/apidb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    #open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 600MB
logging:
  level:
    root: warn
springdoc:
  paths-to-match:
  - /api/**
  swagger-ui:
    use-root-path: true

cors:
  originPatterns: http://localhost:8080,http://localhost:3000
file:
  upload-dir: /home/noki/Documentos/api/upload