spring:
  application:
    name: rest-api
  datasource:
    url: jdbc:postgresql://localhost:5432/apidb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    #open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 600MB
logging:
  level:
    root: warn
springdoc:
  paths-to-match:
  - /api/**
  swagger-ui:
    use-root-path: true

cors:
  originPatterns: http://localhost:8080,http://localhost:3000
file:
  upload-dir: /home/noki/Documentos/api/upload
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
email:
  subject: "Default Subject"
  message: "Default Message"